### ISSUE TITLE
HacktoberFest 2023

### ISSUE THREAD

**Issue by mr-ayush-agrawal** [mr-ayush-agrawal/Hacktoberfest#14]
Open for any kind of Pull Request in the following languages
1. C++
1. Java
1. Python
1. JavaScript
1. C
1. Dart
1. Bash

Do Follow the **Rules** 
- Add the Code in the correct directory
- File naming should be proper. If a language has a particular program do not spam the same code
-  LeetCode and CodeChef Problems are also acceptable. For this don't forget to add a direct link to the question.

## 😄 Happy Hacking

**Comment by praptisharma28** [comment]
HEY @mr-ayush-agrawal , I want to contribute here but I just want to know what exacty you need? Do you want me to add more probems along wit solutions in different languages or do I need to provide the code for the existing files only? I know oython, C, C++ well.

**Comment by NidhiSingh26** [comment]
Hi @mr-ayush-agrawal , I want to contribute here.

**Comment by SusovanDas19** [comment]
hi @mr-ayush-agrawal , I just submitted a pull request for Leetcode question 2025. Please check it out.
 And very happy to contribute in my first ever contribution to the open-source world.

**Comment by mr-ayush-agrawal** [comment]
Hey @praptisharma28 , 
You contribute anything. To keep it easy I have also provided the Options to submit the [LeetCode Problems](leetcode.com/problemset/all/). If You have solved any you can add that solution.

If not you can add any program may be small or large doesn't matter. 
For your reference it could be like :
- Checking if a number is Armstrong or not.
- Performing Linear Search/ Binary Search in Array 
- Reversing a array or anything which comes to your mind

When contributing make sure to follow the Rules of the Repo.

🥳 Happy Hacking

**Comment by praptisharma28** [comment]
I have made a PR, added python programs, please check. Thankyou for replying.

**Comment by itssiddhantjain** [comment]
Hey @mr-ayush-agrawal please assign me this issue.

**Comment by vamus092** [comment]
Hi i want to contribute to JAVA program section making a calculator

**Comment by mr-ayush-agrawal** [comment]
Hi @vamus092,
You are free to contribute in any language of your choice. Just make sure to follow the rules of the repo. :)

**Comment by RashiJyotishi** [comment]
Hi, @mr-ayush-agrawal please assign this issue to me.
