### ISSUE TITLE
Minimum Insertion Steps to Make a String Palindrome

### ISSUE THREAD

**Issue by sujanrupu** [mr-ayush-agrawal/Hacktoberfest#27]
As a Hacktoberfest '23 contributor, I want to add the code from leetcode

- Link: https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/description/
- Language: C++
- Concept: Dynamic Programming

**Comment by mr-ayush-agrawal** [comment]
You can just open a pull request in the repo I will look into it.
